import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["IBM Plex Sans Arabic", "Inter", "system-ui", "sans-serif"],
        display: ["Tajawal", "Inter", "system-ui", "sans-serif"],
        arabic: ["IBM Plex Sans Arabic", "Tajawal", "sans-serif"],
        latin: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // ── Material Design 3 Tonal Palette ──────────────────────────
        md: {
          primary:            "hsl(var(--md-primary))",
          "on-primary":       "hsl(var(--md-on-primary))",
          "primary-container":"hsl(var(--md-primary-container))",
          "on-primary-container":"hsl(var(--md-on-primary-container))",
          secondary:          "hsl(var(--md-secondary))",
          "on-secondary":     "hsl(var(--md-on-secondary))",
          "secondary-container":"hsl(var(--md-secondary-container))",
          "on-secondary-container":"hsl(var(--md-on-secondary-container))",
          tertiary:           "hsl(var(--md-tertiary))",
          "on-tertiary":      "hsl(var(--md-on-tertiary))",
          "tertiary-container":"hsl(var(--md-tertiary-container))",
          "on-tertiary-container":"hsl(var(--md-on-tertiary-container))",
          error:              "hsl(var(--md-error))",
          "on-error":         "hsl(var(--md-on-error))",
          "error-container":  "hsl(var(--md-error-container))",
          "on-error-container":"hsl(var(--md-on-error-container))",
          surface:            "hsl(var(--md-surface))",
          "on-surface":       "hsl(var(--md-on-surface))",
          "surface-variant":  "hsl(var(--md-surface-variant))",
          "on-surface-variant":"hsl(var(--md-on-surface-variant))",
          "surface-container-lowest": "hsl(var(--md-surface-container-lowest))",
          "surface-container-low":    "hsl(var(--md-surface-container-low))",
          "surface-container":        "hsl(var(--md-surface-container))",
          "surface-container-high":   "hsl(var(--md-surface-container-high))",
          "surface-container-highest":"hsl(var(--md-surface-container-highest))",
          "inverse-surface":  "hsl(var(--md-inverse-surface))",
          "inverse-on-surface":"hsl(var(--md-inverse-on-surface))",
          "inverse-primary":  "hsl(var(--md-inverse-primary))",
          outline:            "hsl(var(--md-outline))",
          "outline-variant":  "hsl(var(--md-outline-variant))",
          shadow:             "hsl(var(--md-shadow))",
          scrim:              "hsl(var(--md-scrim))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "md3-xs":  "4px",
        "md3-sm":  "8px",
        "md3-md":  "12px",
        "md3-lg":  "16px",
        "md3-xl":  "28px",
        "md3-2xl": "32px",
        "md3-full":"9999px",
      },
      boxShadow: {
        "md3-1": "0px 1px 2px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)",
        "md3-2": "0px 1px 2px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)",
        "md3-3": "0px 1px 3px rgba(0,0,0,0.3), 0px 4px 8px 3px rgba(0,0,0,0.15)",
        "md3-4": "0px 2px 3px rgba(0,0,0,0.3), 0px 6px 10px 4px rgba(0,0,0,0.15)",
        "md3-5": "0px 4px 4px rgba(0,0,0,0.3), 0px 8px 12px 6px rgba(0,0,0,0.15)",
      },
      fontSize: {
        "md3-display-lg":  ["57px", { lineHeight: "64px", letterSpacing: "-0.25px", fontWeight: "400" }],
        "md3-display-md":  ["45px", { lineHeight: "52px", letterSpacing: "0px",     fontWeight: "400" }],
        "md3-display-sm":  ["36px", { lineHeight: "44px", letterSpacing: "0px",     fontWeight: "400" }],
        "md3-headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0px",     fontWeight: "400" }],
        "md3-headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0px",     fontWeight: "400" }],
        "md3-headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "0px",     fontWeight: "400" }],
        "md3-title-lg":    ["22px", { lineHeight: "28px", letterSpacing: "0px",     fontWeight: "500" }],
        "md3-title-md":    ["16px", { lineHeight: "24px", letterSpacing: "0.15px",  fontWeight: "500" }],
        "md3-title-sm":    ["14px", { lineHeight: "20px", letterSpacing: "0.1px",   fontWeight: "500" }],
        "md3-body-lg":     ["16px", { lineHeight: "24px", letterSpacing: "0.5px",   fontWeight: "400" }],
        "md3-body-md":     ["14px", { lineHeight: "20px", letterSpacing: "0.25px",  fontWeight: "400" }],
        "md3-body-sm":     ["12px", { lineHeight: "16px", letterSpacing: "0.4px",   fontWeight: "400" }],
        "md3-label-lg":    ["14px", { lineHeight: "20px", letterSpacing: "0.1px",   fontWeight: "500" }],
        "md3-label-md":    ["12px", { lineHeight: "16px", letterSpacing: "0.5px",   fontWeight: "500" }],
        "md3-label-sm":    ["11px", { lineHeight: "16px", letterSpacing: "0.5px",   fontWeight: "500" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-4px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(4px)" },
        },
        "md3-ripple": {
          "0%":   { transform: "scale(0)", opacity: "0.35" },
          "100%": { transform: "scale(4)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "spin-slow": "spin 3s linear infinite",
        "shake": "shake 0.5s ease-in-out",
        "md3-ripple": "md3-ripple 600ms linear",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
