import { useState, useEffect, useMemo, useCallback } from "react";
import { useLocation, Link } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  HelpCircle,
  X,
  Sparkles,
  ChevronDown,
  CheckCircle2,
  Copy,
  Check,
  Search,
  ExternalLink,
  Lightbulb,
  ArrowRight,
  Minimize2,
  Maximize2,
  BookOpen,
  MousePointerClick,
  Layers,
  HelpCircle as QuestionIcon
} from "lucide-react";
import { useI18n } from "@/contexts/I18nContext";
import { useToast } from "@/hooks/use-toast";
import { SCREEN_GUIDES, getGuideForPath, ScreenGuideItem } from "@/data/screenGuidesData";
import { cn } from "@/lib/utils";

export default function ScreenGuideHelper() {
  const location = useLocation();
  const { locale, dir } = useI18n();
  const { toast } = useToast();

  const isEn = locale === "en";

  // Active guide (detected from URL by default)
  const currentDetectedGuide = useMemo(
    () => getGuideForPath(location.pathname),
    [location.pathname]
  );

  const [isOpen, setIsOpen] = useState(false);
  const [selectedGuideId, setSelectedGuideId] = useState<string>(currentDetectedGuide.id);
  const [activeTab, setActiveTab] = useState<"steps" | "buttons" | "tips" | "all">("steps");
  const [isMinimized, setIsMinimized] = useState<boolean>(() => {
    return localStorage.getItem("tx_guide_minimized") === "true";
  });
  const [completedSteps, setCompletedSteps] = useState<Record<string, number[]>>({});
  const [searchQuery, setSearchQuery] = useState("");
  const [copied, setCopied] = useState(false);

  // Sync selected guide when path changes
  useEffect(() => {
    setSelectedGuideId(currentDetectedGuide.id);
  }, [currentDetectedGuide.id]);

  // Listen to custom event to open guide from Header or elsewhere
  useEffect(() => {
    const handleOpenEvent = () => setIsOpen(true);
    window.addEventListener("open-screen-guide", handleOpenEvent);
    return () => window.removeEventListener("open-screen-guide", handleOpenEvent);
  }, []);

  // Keyboard shortcut: Shift + ? or Alt + H to toggle
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.shiftKey && e.key === "?") || (e.altKey && e.key.toLowerCase() === "h")) {
        // If not typing in input/textarea
        if (
          document.activeElement?.tagName !== "INPUT" &&
          document.activeElement?.tagName !== "TEXTAREA"
        ) {
          e.preventDefault();
          setIsOpen(prev => !prev);
        }
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Save minimize preference
  const toggleMinimize = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsMinimized(prev => {
      const next = !prev;
      localStorage.setItem("tx_guide_minimized", String(next));
      return next;
    });
  };

  // Active guide being viewed
  const activeGuide: ScreenGuideItem = useMemo(() => {
    return SCREEN_GUIDES.find(g => g.id === selectedGuideId) || currentDetectedGuide;
  }, [selectedGuideId, currentDetectedGuide]);

  // Toggle step completion checkbox
  const toggleStepDone = (stepNumber: number) => {
    setCompletedSteps(prev => {
      const currentDone = prev[activeGuide.id] || [];
      const updated = currentDone.includes(stepNumber)
        ? currentDone.filter(s => s !== stepNumber)
        : [...currentDone, stepNumber];
      return { ...prev, [activeGuide.id]: updated };
    });
  };

  // Copy steps to clipboard
  const handleCopySteps = useCallback(() => {
    const textLines = [
      `📘 ${isEn ? activeGuide.titleEn : activeGuide.titleAr}`,
      isEn ? activeGuide.summaryEn : activeGuide.summaryAr,
      "",
      isEn ? "--- Actionable Steps ---" : "--- خطوات العمل الإجرائية ---",
      ...activeGuide.steps.map(s => 
        `${s.stepNumber}. ${isEn ? s.titleEn : s.titleAr}\n   ${isEn ? s.actionEn : s.actionAr}\n   ${isEn ? "Expected: " + s.expectedOutcomeEn : "النتيجة المتوقعة: " + s.expectedOutcomeAr}`
      ),
      "",
      isEn ? "Generated by Tawzeef-X Guide" : "تم الاستخراج من دليل نظام Tawzeef-X"
    ].join("\n");

    navigator.clipboard.writeText(textLines);
    setCopied(true);
    toast({
      title: isEn ? "Steps copied to clipboard! 📋" : "تم نسخ خطوات العمل إلى الحافظة! 📋",
      description: isEn ? "You can paste these instructions anywhere." : "يمكنك مشاركة هذه الخطوات مع أي عضو في الفريق."
    });
    setTimeout(() => setCopied(false), 2500);
  }, [activeGuide, isEn, toast]);

  // Filtered guides for the "All Screens" tab
  const filteredAllGuides = useMemo(() => {
    if (!searchQuery.trim()) return SCREEN_GUIDES;
    const q = searchQuery.toLowerCase();
    return SCREEN_GUIDES.filter(
      g =>
        g.titleAr.toLowerCase().includes(q) ||
        g.titleEn.toLowerCase().includes(q) ||
        g.summaryAr.toLowerCase().includes(q) ||
        g.summaryEn.toLowerCase().includes(q)
    );
  }, [searchQuery]);

  const ActiveIcon = activeGuide.icon;

  return (
    <>
      {/* 1. FLOATING TRIGGER BUTTON ON THE SCREEN SIDE */}
      <div
        className={cn(
          "fixed z-40 transition-all duration-300 pointer-events-auto",
          dir === "rtl" ? "left-6" : "right-6",
          "bottom-20 lg:bottom-6"
        )}
      >
        <AnimatePresence mode="wait">
          {!isMinimized ? (
            <motion.div
              key="expanded-pill"
              initial={{ opacity: 0, scale: 0.8, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.8, y: 15 }}
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              className="relative group flex items-center"
            >
              {/* Subtle Pulsing Ping Ring */}
              <span className="absolute -top-1 -right-1 flex h-3.5 w-3.5">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                <span className="relative inline-flex rounded-full h-3.5 w-3.5 bg-emerald-500" />
              </span>

              {/* Main Pill Button */}
              <button
                onClick={() => setIsOpen(true)}
                className={cn(
                  "flex items-center gap-2.5 px-4 py-2.5 rounded-full shadow-lg transition-all",
                  "bg-gradient-to-r from-emerald-600 via-teal-600 to-emerald-700 text-white",
                  "hover:shadow-emerald-500/25 hover:shadow-xl border border-white/20",
                  "backdrop-blur-md"
                )}
                title={isEn ? "Open Screen Guide (Shift + ?)" : "افتح دليل هذه الشاشة (Shift + ?)"}
              >
                <div className="w-6 h-6 rounded-full bg-white/20 flex items-center justify-center">
                  <Sparkles className="w-3.5 h-3.5 text-white animate-pulse" />
                </div>
                <div className="text-right">
                  <p className="text-xs font-black tracking-wide leading-none">
                    {isEn ? "Screen Guide" : "دليل الشاشة"}
                  </p>
                  <p className="text-[10px] text-emerald-100/90 font-medium leading-tight max-w-[120px] truncate">
                    {isEn ? currentDetectedGuide.titleEn : currentDetectedGuide.titleAr}
                  </p>
                </div>
              </button>

              {/* Minimize action button */}
              <button
                onClick={toggleMinimize}
                className="absolute -top-2 -left-2 w-5 h-5 rounded-full bg-card border border-border text-muted-foreground hover:text-foreground flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity shadow-sm"
                title={isEn ? "Minimize button" : "تصغير الزر"}
              >
                <Minimize2 className="w-3 h-3" />
              </button>
            </motion.div>
          ) : (
            <motion.div
              key="minimized-bubble"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.5 }}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              className="relative group"
            >
              <button
                onClick={() => setIsOpen(true)}
                className="w-12 h-12 rounded-full bg-gradient-to-br from-emerald-600 to-teal-700 text-white shadow-lg border border-white/25 flex items-center justify-center hover:shadow-emerald-500/30 hover:shadow-xl transition-all"
                title={isEn ? "Open Screen Guide" : "افتح دليل الشاشة"}
              >
                <Sparkles className="w-5 h-5 text-white" />
              </button>
              <button
                onClick={toggleMinimize}
                className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-card border border-border text-muted-foreground hover:text-foreground flex items-center justify-center shadow-xs"
                title={isEn ? "Expand button" : "تكبير الزر"}
              >
                <Maximize2 className="w-2.5 h-2.5" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* 2. LARGE POPUP MODAL (CONTEXTUAL SCREEN GUIDE) */}
      <AnimatePresence>
        {isOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 select-text overflow-hidden">
            {/* Backdrop Blur Overlay */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsOpen(false)}
              className="fixed inset-0 bg-black/60 backdrop-blur-md transition-opacity"
            />

            {/* Modal Dialog Container */}
            <motion.div
              initial={{ opacity: 0, scale: 0.93, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.93, y: 20 }}
              transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
              className={cn(
                "relative z-10 w-full max-w-4xl max-h-[90vh] flex flex-col",
                "bg-card/95 backdrop-blur-2xl border border-border/70 shadow-2xl rounded-3xl overflow-hidden",
                "text-card-foreground",
                dir === "rtl" ? "text-right" : "text-left"
              )}
              dir={dir}
            >
              {/* Modal Top Header */}
              <div className="flex items-center justify-between p-5 sm:p-6 border-b border-border/50 bg-gradient-to-b from-muted/30 to-transparent">
                {/* Screen Icon + Title & Category */}
                <div className="flex items-center gap-3.5 min-w-0">
                  <div
                    className={cn(
                      "w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 border shadow-xs",
                      activeGuide.bg,
                      activeGuide.border
                    )}
                  >
                    <ActiveIcon className={cn("w-6 h-6", activeGuide.color)} />
                  </div>
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h2 className="text-lg sm:text-xl font-black text-foreground truncate">
                        {isEn ? activeGuide.titleEn : activeGuide.titleAr}
                      </h2>
                      <span
                        className={cn(
                          "px-2.5 py-0.5 rounded-full text-[11px] font-bold border",
                          activeGuide.bg,
                          activeGuide.color,
                          activeGuide.border
                        )}
                      >
                        {isEn ? activeGuide.badgeEn : activeGuide.badgeAr}
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5 truncate">
                      {isEn ? `Target Audience: ${activeGuide.targetAudienceEn}` : `الفئة المستهدفة: ${activeGuide.targetAudienceAr}`}
                    </p>
                  </div>
                </div>

                {/* Right Header Actions */}
                <div className="flex items-center gap-2 shrink-0">
                  {/* Quick Screen Switcher Dropdown */}
                  <div className="relative">
                    <select
                      value={activeGuide.id}
                      onChange={e => setSelectedGuideId(e.target.value)}
                      className="bg-muted hover:bg-muted/80 text-foreground text-xs font-semibold py-1.5 px-3 rounded-xl border border-border/60 outline-none cursor-pointer transition-colors max-w-[140px] sm:max-w-[200px] truncate"
                      title={isEn ? "Switch to guide of another screen" : "تبديل لشاشة أخرى"}
                    >
                      {SCREEN_GUIDES.map(g => (
                        <option key={g.id} value={g.id}>
                          {isEn ? g.titleEn : g.titleAr}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Copy Steps Button */}
                  <button
                    onClick={handleCopySteps}
                    className="p-2 rounded-xl bg-muted hover:bg-muted/80 text-muted-foreground hover:text-foreground transition-colors"
                    title={isEn ? "Copy steps text" : "نسخ خطوات العمل"}
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                  </button>

                  {/* Close Modal Button */}
                  <button
                    onClick={() => setIsOpen(false)}
                    className="p-2 rounded-xl bg-muted hover:bg-destructive/15 text-muted-foreground hover:text-destructive transition-colors"
                    title={isEn ? "Close guide (Esc)" : "إغلاق الدليل"}
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Sub-Header: Objective & Summary Card */}
              <div className="px-5 sm:px-6 py-3.5 bg-muted/40 border-b border-border/40 flex items-start gap-3">
                <div className="w-7 h-7 rounded-lg bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 flex items-center justify-center shrink-0 mt-0.5">
                  <Lightbulb className="w-4 h-4" />
                </div>
                <p className="text-xs sm:text-sm text-foreground/90 font-medium leading-relaxed">
                  {isEn ? activeGuide.summaryEn : activeGuide.summaryAr}
                </p>
              </div>

              {/* Interactive Tabs Bar */}
              <div className="flex items-center gap-2 px-5 sm:px-6 border-b border-border/50 bg-background/50 overflow-x-auto no-scrollbar">
                <button
                  onClick={() => setActiveTab("steps")}
                  className={cn(
                    "flex items-center gap-2 py-3 px-3.5 text-xs sm:text-sm font-bold border-b-2 transition-all whitespace-nowrap",
                    activeTab === "steps"
                      ? "border-emerald-500 text-emerald-600 dark:text-emerald-400"
                      : "border-transparent text-muted-foreground hover:text-foreground"
                  )}
                >
                  <MousePointerClick className="w-4 h-4" />
                  <span>{isEn ? "Action Steps (1, 2, 3...)" : "خطوات العمل الإجرائية (١، ٢، ٣...)"}</span>
                  <span className="bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 text-[10px] px-1.5 py-0.5 rounded-full">
                    {activeGuide.steps.length}
                  </span>
                </button>

                <button
                  onClick={() => setActiveTab("buttons")}
                  className={cn(
                    "flex items-center gap-2 py-3 px-3.5 text-xs sm:text-sm font-bold border-b-2 transition-all whitespace-nowrap",
                    activeTab === "buttons"
                      ? "border-emerald-500 text-emerald-600 dark:text-emerald-400"
                      : "border-transparent text-muted-foreground hover:text-foreground"
                  )}
                >
                  <Layers className="w-4 h-4" />
                  <span>{isEn ? "Key Buttons & Actions" : "أهم الأزرار والإجراءات"}</span>
                  <span className="bg-muted text-muted-foreground text-[10px] px-1.5 py-0.5 rounded-full">
                    {activeGuide.keyButtons.length}
                  </span>
                </button>

                <button
                  onClick={() => setActiveTab("tips")}
                  className={cn(
                    "flex items-center gap-2 py-3 px-3.5 text-xs sm:text-sm font-bold border-b-2 transition-all whitespace-nowrap",
                    activeTab === "tips"
                      ? "border-emerald-500 text-emerald-600 dark:text-emerald-400"
                      : "border-transparent text-muted-foreground hover:text-foreground"
                  )}
                >
                  <QuestionIcon className="w-4 h-4" />
                  <span>{isEn ? "Pro Tips & FAQs" : "أسرار العمل وحلول المشاكل"}</span>
                  <span className="bg-amber-500/15 text-amber-600 dark:text-amber-400 text-[10px] px-1.5 py-0.5 rounded-full">
                    {activeGuide.proTips.length + activeGuide.faqs.length}
                  </span>
                </button>

                <button
                  onClick={() => setActiveTab("all")}
                  className={cn(
                    "flex items-center gap-2 py-3 px-3.5 text-xs sm:text-sm font-bold border-b-2 transition-all whitespace-nowrap",
                    activeTab === "all"
                      ? "border-emerald-500 text-emerald-600 dark:text-emerald-400"
                      : "border-transparent text-muted-foreground hover:text-foreground"
                  )}
                >
                  <BookOpen className="w-4 h-4" />
                  <span>{isEn ? "All System Screens" : "دليل كافة الشاشات"}</span>
                  <span className="bg-muted text-muted-foreground text-[10px] px-1.5 py-0.5 rounded-full">
                    {SCREEN_GUIDES.length}
                  </span>
                </button>
              </div>

              {/* Modal Body Scroll Area */}
              <div className="flex-1 overflow-y-auto p-5 sm:p-6 space-y-4 max-h-[55vh]">
                {/* TAB 1: STEP-BY-STEP ACTION WORKFLOW */}
                {activeTab === "steps" && (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between pb-1">
                      <p className="text-xs font-semibold text-muted-foreground">
                        {isEn
                          ? "Follow these clear steps to complete your tasks on this screen without contacting support:"
                          : "اتبع هذه الخطوات بالترتيب لتشغيل وإنجاز عملك على هذه الشاشة دون الحاجة لسؤال أي شخص:"}
                      </p>
                      <span className="text-[11px] text-emerald-600 dark:text-emerald-400 font-bold">
                        {(completedSteps[activeGuide.id] || []).length} / {activeGuide.steps.length}{" "}
                        {isEn ? "Completed" : "مكتمل"}
                      </span>
                    </div>

                    <div className="space-y-3.5">
                      {activeGuide.steps.map(step => {
                        const isDone = (completedSteps[activeGuide.id] || []).includes(step.stepNumber);
                        return (
                          <div
                            key={step.stepNumber}
                            onClick={() => toggleStepDone(step.stepNumber)}
                            className={cn(
                              "p-4 rounded-2xl border transition-all cursor-pointer group",
                              isDone
                                ? "bg-emerald-500/5 border-emerald-500/30 opacity-90"
                                : "bg-card border-border/70 hover:border-emerald-500/50 hover:shadow-xs"
                            )}
                          >
                            <div className="flex items-start gap-3.5">
                              {/* Step Number Circle / Checkbox */}
                              <div
                                className={cn(
                                  "w-8 h-8 rounded-full flex items-center justify-center text-xs font-black shrink-0 transition-colors shadow-2xs mt-0.5",
                                  isDone
                                    ? "bg-emerald-500 text-white"
                                    : "bg-muted text-foreground group-hover:bg-emerald-500/20 group-hover:text-emerald-600"
                                )}
                              >
                                {isDone ? <Check className="w-4 h-4" /> : step.stepNumber}
                              </div>

                              <div className="flex-1 min-w-0 space-y-2">
                                <div className="flex items-center justify-between gap-2">
                                  <h3
                                    className={cn(
                                      "text-sm sm:text-base font-bold text-foreground",
                                      isDone && "line-through text-muted-foreground"
                                    )}
                                  >
                                    {isEn ? step.titleEn : step.titleAr}
                                  </h3>
                                  <span className="text-[11px] text-muted-foreground group-hover:text-emerald-500 flex items-center gap-1 shrink-0">
                                    {isDone
                                      ? isEn ? "Done" : "تمت الخطوة"
                                      : isEn ? "Click to mark done" : "اضغط للتعليم كمكتمل"}
                                  </span>
                                </div>

                                {/* Step Action Description */}
                                <p className="text-xs sm:text-sm text-foreground/80 leading-relaxed">
                                  {isEn ? step.actionEn : step.actionAr}
                                </p>

                                {/* Expected Outcome Badge */}
                                <div className="p-2.5 rounded-xl bg-muted/60 border border-border/40 flex items-start gap-2">
                                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                                  <div className="text-xs">
                                    <span className="font-bold text-emerald-600 dark:text-emerald-400">
                                      {isEn ? "Expected Outcome: " : "النتيجة المؤكدة: "}
                                    </span>
                                    <span className="text-foreground/90">
                                      {isEn ? step.expectedOutcomeEn : step.expectedOutcomeAr}
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                {/* TAB 2: KEY BUTTONS & ACTIONS MAP */}
                {activeTab === "buttons" && (
                  <div className="space-y-4">
                    <p className="text-xs font-semibold text-muted-foreground">
                      {isEn
                        ? "Guide to all major buttons and actionable controls on this screen:"
                        : "شرح شامل لكافة الأزرار والأدوات التفاعلية المتاحة في هذه الشاشة وماذا تفعل:"}
                    </p>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {activeGuide.keyButtons.map((btn, idx) => (
                        <div
                          key={idx}
                          className="p-4 rounded-2xl bg-card border border-border/70 hover:border-emerald-500/40 transition-all flex flex-col justify-between space-y-2 shadow-2xs"
                        >
                          <div className="flex items-center gap-2">
                            <span
                              className={cn(
                                "w-2.5 h-2.5 rounded-full shrink-0",
                                btn.actionType === "primary"
                                  ? "bg-emerald-500"
                                  : btn.actionType === "action"
                                  ? "bg-blue-500"
                                  : "bg-amber-500"
                              )}
                            />
                            <h4 className="text-xs sm:text-sm font-bold text-foreground">
                              {isEn ? btn.nameEn : btn.nameAr}
                            </h4>
                          </div>
                          <p className="text-xs text-muted-foreground leading-relaxed">
                            {isEn ? btn.descriptionEn : btn.descriptionAr}
                          </p>
                        </div>
                      ))}
                    </div>

                    {/* Quick navigation links to related screens */}
                    {activeGuide.quickLinks && activeGuide.quickLinks.length > 0 && (
                      <div className="mt-5 p-4 rounded-2xl bg-muted/40 border border-border/50">
                        <p className="text-xs font-bold text-foreground mb-2.5">
                          {isEn ? "🔗 Related Quick Screens:" : "🔗 شاشات مرتبطة يمكنك الانتقال إليها فوراً:"}
                        </p>
                        <div className="flex items-center gap-2 flex-wrap">
                          {activeGuide.quickLinks.map((link, idx) => (
                            <Link
                              key={idx}
                              to={link.path}
                              onClick={() => setIsOpen(false)}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-card border border-border/70 text-xs font-bold text-foreground hover:text-emerald-500 hover:border-emerald-500/40 transition-all"
                            >
                              <span>{isEn ? link.labelEn : link.labelAr}</span>
                              <ArrowRight className="w-3 h-3 text-emerald-500" />
                            </Link>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* TAB 3: PRO TIPS & FAQS */}
                {activeTab === "tips" && (
                  <div className="space-y-5">
                    {/* Pro Tips Section */}
                    {activeGuide.proTips.length > 0 && (
                      <div className="space-y-3">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400 flex items-center gap-1.5">
                          <Lightbulb className="w-4 h-4" />
                          <span>{isEn ? "Pro Tips & Best Practices" : "نصائح وأسرار الاستخدام الاحترافي"}</span>
                        </h4>
                        <div className="grid grid-cols-1 gap-3">
                          {activeGuide.proTips.map((tip, idx) => (
                            <div
                              key={idx}
                              className="p-4 rounded-2xl bg-amber-500/5 border border-amber-500/20 text-xs sm:text-sm space-y-1"
                            >
                              <p className="font-bold text-foreground">
                                {isEn ? tip.titleEn : tip.titleAr}
                              </p>
                              <p className="text-muted-foreground leading-relaxed">
                                {isEn ? tip.descriptionEn : tip.descriptionAr}
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* FAQs Section */}
                    {activeGuide.faqs.length > 0 && (
                      <div className="space-y-3 pt-2">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-foreground flex items-center gap-1.5">
                          <QuestionIcon className="w-4 h-4 text-emerald-500" />
                          <span>{isEn ? "Troubleshooting & FAQs" : "الأسئلة الشائعة وحلول المشكلات"}</span>
                        </h4>
                        <div className="space-y-2.5">
                          {activeGuide.faqs.map((faq, idx) => (
                            <div
                              key={idx}
                              className="p-4 rounded-2xl bg-card border border-border/70 space-y-1.5"
                            >
                              <p className="text-xs sm:text-sm font-bold text-foreground flex items-center gap-2">
                                <span className="text-emerald-500 font-black">س:</span>
                                <span>{isEn ? faq.qEn : faq.qAr}</span>
                              </p>
                              <p className="text-xs text-muted-foreground leading-relaxed pl-4">
                                <span className="text-emerald-600 font-bold">ج: </span>
                                <span>{isEn ? faq.aEn : faq.aAr}</span>
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* TAB 4: ALL SYSTEM SCREENS DIRECTORY */}
                {activeTab === "all" && (
                  <div className="space-y-4">
                    {/* Search Filter */}
                    <div className="relative">
                      <Search className="w-4 h-4 absolute top-1/2 -translate-y-1/2 right-3.5 text-muted-foreground" />
                      <input
                        type="text"
                        value={searchQuery}
                        onChange={e => setSearchQuery(e.target.value)}
                        placeholder={isEn ? "Search any screen or tool..." : "ابحث عن أي شاشة أو أداة في النظام..."}
                        className="w-full h-10 pr-10 pl-4 rounded-xl bg-muted/60 border border-border/70 text-xs sm:text-sm focus:outline-none focus:border-emerald-500/60"
                      />
                    </div>

                    {/* Screen Grid */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
                      {filteredAllGuides.map(item => {
                        const ItemIcon = item.icon;
                        const isSelected = item.id === activeGuide.id;
                        return (
                          <div
                            key={item.id}
                            onClick={() => {
                              setSelectedGuideId(item.id);
                              setActiveTab("steps");
                            }}
                            className={cn(
                              "p-3.5 rounded-2xl border transition-all cursor-pointer flex items-center justify-between gap-3",
                              isSelected
                                ? "bg-emerald-500/10 border-emerald-500 shadow-2xs"
                                : "bg-card border-border/70 hover:border-emerald-500/40 hover:bg-muted/30"
                            )}
                          >
                            <div className="flex items-center gap-3 min-w-0">
                              <div
                                className={cn(
                                  "w-9 h-9 rounded-xl flex items-center justify-center shrink-0 border",
                                  item.bg,
                                  item.border
                                )}
                              >
                                <ItemIcon className={cn("w-4 h-4", item.color)} />
                              </div>
                              <div className="min-w-0">
                                <p className="text-xs sm:text-sm font-bold text-foreground truncate">
                                  {isEn ? item.titleEn : item.titleAr}
                                </p>
                                <p className="text-[11px] text-muted-foreground truncate">
                                  {isEn ? item.badgeEn : item.badgeAr}
                                </p>
                              </div>
                            </div>

                            <button className="text-xs text-emerald-600 dark:text-emerald-400 font-bold shrink-0 hover:underline">
                              {isEn ? "View Guide" : "عرض الدليل"}
                            </button>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
              </div>

              {/* Modal Bottom Footer */}
              <div className="p-4 sm:p-5 border-t border-border/50 bg-muted/30 flex items-center justify-between gap-3 flex-wrap">
                <div className="flex items-center gap-2">
                  <Link
                    to="/tutorial"
                    onClick={() => setIsOpen(false)}
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-muted hover:bg-muted/80 text-foreground text-xs font-bold transition-all border border-border/60"
                  >
                    <BookOpen className="w-3.5 h-3.5 text-emerald-500" />
                    <span>{isEn ? "Full System Tutorial (16 Modules)" : "دليل النظام بالكامل (١٦ قسماً)"}</span>
                  </Link>
                </div>

                <div className="flex items-center gap-2.5">
                  <button
                    onClick={handleCopySteps}
                    className="px-4 py-2 rounded-xl bg-muted hover:bg-muted/80 text-foreground text-xs font-bold transition-all flex items-center gap-1.5"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    <span>{copied ? (isEn ? "Copied!" : "تم النسخ!") : (isEn ? "Copy Steps" : "نسخ الخطوات")}</span>
                  </button>

                  <button
                    onClick={() => setIsOpen(false)}
                    className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-sm transition-all"
                  >
                    {isEn ? "I'm Ready, Start Working" : "فهمت الخطوات، ابدأ العمل الآن"}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}
